### ISSUE TITLE
Cannot add icon in Nameless AdminCP > Configuration > Navigation 

### ISSUE THREAD

**Issue by siriuscraft-MCAdmin** [CraftingStore/NamelessMC-CraftingStore#12]
The icon field for CraftingStore will not save the data, to be able to display an icon on the Navbar. I renamed my Crafting Store to Mahane Market in the language file, but that is the only change I made to the direct files. 

![image](https://user-images.githubusercontent.com/74017935/104657252-40574680-5686-11eb-833c-226a95d62f4c.png)

**Comment by Tim-NL** [comment]
Hi,

The latest release (https://github.com/CraftingStore/NamelessMC-CraftingStore/releases/tag/1.3) will now support this feature.

Thanks for creating the issue.

-Tim
