### ISSUE TITLE
Cannot set icon field for CraftingStore in Namelesss Navigation

### ISSUE THREAD

**Issue by siriuscraft-MCAdmin** [CraftingStore/NamelessMC-CraftingStore#13]
The icon field for CraftingStore will not save the data, to be able to display an icon on the Navbar. I renamed my Crafting Store to Mahane Market in the language file, but that is the only change I made to the direct files. This would be really cool to be functioning. 

![image](https://user-images.githubusercontent.com/74017935/104657252-40574680-5686-11eb-833c-226a95d62f4c.png)

**Comment by Tim-NL** [comment]
Duplicate with your other ticket.

-Tim

**Comment by siriuscraft-MCAdmin** [comment]
opp, sorry, my breowser gave me a 404 when i submitted.

**Comment by Tim-NL** [comment]
Someone else also submitted two issues to our other repo, so I think it's a Github issue. No worries.

-Tim
