### ISSUE TITLE
Buy Button

### ISSUE THREAD

**Issue by an4k1nz** [CraftingStore/NamelessMC-CraftingStore#17]
Upon pressing the buy button, it sends you to a website just including what I assume to be the place it is supposed to go, but forgetting the domain and stuff- 
![image](https://user-images.githubusercontent.com/29868779/119709612-057ad180-be23-11eb-9b82-91a7ec277169.png)

**Comment by Tim-NL** [comment]
Hi,

This means that you did not configure a domain just yet on our dashboard. If you did, please open a ticket on our dashboard. This is not a global issue, it is a configuration issue.

-Tim
