### ISSUE TITLE
Error Sync

### ISSUE THREAD

**Issue by ZynxOG** [CraftingStore/NamelessMC-CraftingStore#7]
I am having a hard time getting my store to sync with my NamelessMC website, I follow the instructions on how to install and make sure I have all the perms needed but when I try to click on any of the modules settings/options it brings me to a 404 error page on my website saying that the page cant be found. Please let me know if you might know what I have done wrong..

My Discord tag is - KozaFR#0001

**Comment by Tim-NL** [comment]
Hi,

I'm not sure if the issue has been resolved already or not, but if it hasn't, please create a support ticket through our dashboard.

Also, try to reinstall the plugin, if you get a 404, then I think you are missing some files.

-Tim
